defaults:
  - hydra/launcher: script

some_argument: 1

cluster:
  partition: ml
  max_array_tasks: 100

hydra:
  launcher:
    batch_script_template: |
      #!/bin/bash
      #SBATCH --time 0-02:00
      #SBATCH --cpus-per-task 1
      #SBATCH --gres=gpus:0
      #SBATCH --mem-per-cpu=8000
      #SBATCH --job-name test
      #SBATCH --output multirun/2021-05-09/03-01-07/cluster_oe/%A_%x_%t.oe
      #SBATCH --error multirun/2021-05-09/03-01-07/cluster_oe/%A_%x_%t.oe
      #SBATCH --array 0-<PUT_NUM_ARGS>%${cluster.max_array_tasks}
      #SBATCH --partition ${cluster.partition}
      <PUT_ARGS>
      conda activate script
      python example/my_app.py ${ARGS[$SLURM_ARRAY_TASK_ID}}