defaults:
  - hydra/launcher: script

some_argument: 1

cluster:
  partition: ml
  max_array_tasks: 100

hydra:
  launcher:
    pre_command: "mkdir ${hydra.sweep.dir}/cluster_oe -p"
    batch_script_template: |
      #!/bin/bash
      #SBATCH --time 0-01:00
      #SBATCH --job-name test
      #SBATCH --output ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
      #SBATCH --error ${hydra.sweep.dir}/cluster_oe/%A_%x_%t.oe
      #SBATCH --array 1-<PUT_NUM_ARGS>%${cluster.max_array_tasks}
      #SBATCH --partition ${cluster.partition}
      <PUT_ARGS>
      conda activate script
      python example/my_app.py ${ARGS[$SLURM_ARRAY_TASK_ID]}
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H:%M}
    subdir: ${some_argument}